apiVersion: xl-release/v1
kind: Templates
spec:
  - type: xlrelease.ThemeSettings
    id: Configuration/settings/ThemeSettings
    headerName: SDK Environment
    headerAccentColor: ORANGE
    description: Instance for testing plugins build with the Integration SDK
    loginMessage: |-
      Welcome to the Digital.ai Release SDK Environment!
      Use this server to test integrations plugins
